collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6497452827170491
color:
  saturation: 0.20201970357447863
  brandStrength: 0.8731657180469483
  rhythmicContrast: 0.29873061110265553
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  lightness: 0.13971524825319648
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: one earth community
    type: external
layout_spectrum: 0.689044
name: One.Earth Challanged
