layout_spectrum: 0.5195150566287339
typography_spectrum: 0.345743166282773
color:
  saturation: 0.13905446068383753
  lightness: 0.6522993810940534
  brandStrength: 0.7509480870794505
  rhythmicContrast: 0.31127614970318973
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
name: One.Earth Challanged
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: one earth community
    type: external
