collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.4573943060822785
color:
  saturation: 0.8125672
  brandStrength: 0.6442387814167887
  rhythmicContrast: 0.4172932
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  lightness: 0.4688507
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: one earth community
    type: external
layout_spectrum: 0.689044
name: One.Earth Challanged
