collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7429045895114541
color:
  saturation: 0.775870191399008
  brandStrength: 0.30349426274187863
  rhythmicContrast: 0.09277570806443691
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  lightness: 0.9858531828504056
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: one earth community
    type: external
layout_spectrum: 0.689044
name: One.Earth Challanged
