layout_spectrum: 0.09873661235906184
typography_spectrum: 0.10915460623800755
color:
  saturation: 0.34052813332527876
  lightness: 0.23485716828145087
  brandStrength: 0.11149029666557908
  rhythmicContrast: 0.5525287077762187
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
name: One.Earth Challanged
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: one earth community
    type: external
