layout_spectrum: 0.5195150566287339
typography_spectrum: 0.4573943060822785
color:
  saturation: 0.7939953415188938
  lightness: 0.521949031855911
  brandStrength: 0.6442387814167887
  rhythmicContrast: 0.802926346193999
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
name: One.Earth Challanged
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: one earth community
    type: external
