collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4076262
color:
  saturation: 0.07560573727823794
  brandStrength: 0.3182534442748874
  rhythmicContrast: 0.9602731170598418
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  lightness: 0.1300089049618691
navigation:
  - id: 'https://thegrid.ai/one-earth-community/'
    url: 'https://thegrid.ai/one-earth-community/'
    name: one earth community
    type: external
  - id: 'http://thegrid.ai/one-earth-community-challenged-blog/'
    url: 'http://thegrid.ai/one-earth-community-challenged-blog/'
    name: blog
    type: external
layout_spectrum: 0.5996482449118048
name: One Earth Challenged
